I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 202, in script
    show kevin:
Exception: DynamicImage u'Create 2/Hair/Style[STyle11]_[Color11].png': could not find image. (u'Create 2/Hair/Style5_1.png')

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 202, in script
    show kevin:
  File "renpy/ast.py", line 1197, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1167, in show_imspec
    atl=atl)
  File "renpy/exports.py", line 770, in show
    sls.add(layer, img, key, zorder, behind, at_list=at_list, name=name, atl=atl, default_transform=default_transform, transient=transient)
  File "renpy/display/core.py", line 1147, in add
    thing.visit_all(lambda d : None)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 558, in visit_all
    for d in self.visit():
  File "renpy/display/image.py", line 744, in visit
    self.find_target()
  File "renpy/display/image.py", line 652, in find_target
    raise Exception(error)
Exception: DynamicImage u'Create 2/Hair/Style[STyle11]_[Color11].png': could not find image. (u'Create 2/Hair/Style5_1.png')

Windows-10-10.0.22000
Ren'Py 7.4.10.2178
Healthy and Safety 1.0
Wed Jul 20 22:37:44 2022
